application: blackhawk-website
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
#root
- url: /
  static_files: dist/index.html
  upload: dist/index.html
  
#serve our home page in case index.html is requested
- url: /index.html
  static_files: dist/index.html
  upload: dist/index.html

- url: /views/prototype.html
  static_files: dist/views/prototype.html
  upload: dist/views/prototype.html

- url: /views/design.html
  static_files: dist/views/design.html
  upload: dist/views/design.html

- url: /views/develop.html
  static_files: dist/views/develop.html
  upload: dist/views/develop.html

- url: /views/cloud.html
  static_files: dist/views/cloud.html
  upload: dist/views/cloud.html

#all images and support file (css, fonts...): return file if found, 
#otherwise the default 404 page so it can be handled by sites that link
#directly to images.
- url: /(.*\.(js|css|gif|png|jpg|ico|bmp|css|otf|eot|svg|ttf|woff))
  static_files: dist/\1
  upload: dist/(.*\.(js|css|gif|png|jpg|ico|bmp|css|otf|eot|svg|ttf|woff))
  
libraries:
- name: webapp2
  version: "2.5.2"
